### ISSUE TITLE
Dataset Avaiability 

### ISSUE THREAD

**Issue by JMarzoli** [ghigliottin-AI/ghigliottin-AI.github.io#1]
Hello.

Since the link for register a new system doesn't work anymore, i was wondering if it could be possible to have the dataset of the 300 words whit their solution.

I'm working on a thesis that studies NLP, and it could be very useful . 

Thanks.

**Comment by kercos** [comment]
Please get in touch with Marco Lovetere (see email under the organizer section).

**Comment by kercos** [comment]
Dear @JMarzoli, sorry for the late reply.
We finally managed to retrieve the test json file.
Here it is:
[dataset.json](https://github.com/ghigliottin-AI/ghigliottin-AI.github.io/files/13726243/dataset.json)

**Comment by kercos** [comment]
also included it in the README
